http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  cogmaker:
    host: '*'
    paths:
    - '/build_COG/'
    - '/build_zarr/'
  damage:
    host: '*'
    paths:
    - '/damage/dlr_guf/'
  cog2pt:
    host: '*'
    paths:
    - '/zarr2pt/'
  geoparquet2pmtiles:
    host: '*'
    paths:
    - '/create_pmtiles/'
    - '/get_tilesets/'
serviceEndpoints:
  geoparquet2pmtiles:
    url: 'http://molokai.pbsci.ucsc.edu:3004'
  cogmaker:
    url: 'http://molokai.pbsci.ucsc.edu:3002'
  cog2pt:
    url: 'http://molokai.pbsci.ucsc.edu:3003'
  damage:
    url: 'http://molokai.pbsci.ucsc.edu:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  damage:
    apiEndpoints:
      - damage
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: damage
              changeOrigin: true
  cogmaker:
    apiEndpoints:
      - cogmaker
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: cogmaker
              changeOrigin: true
  cog2pt:
    apiEndpoints:
      - cog2pt
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: cog2pt
              changeOrigin: true
  geoparquet2pmtiles:
    apiEndpoints:
      - geoparquet2pmtiles
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: geoparquet2pmtiles
              changeOrigin: true
